name: Build

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # This cannot be higher than the Go version used to build the plugin for
    # release (in canva/infrastructure //app/aws-for-fluent-bit/plugin:plugin).
    # This is currently Go 1.20.
    - name: Set up Go 1.20
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
      id: go

    - name: Install cross-compiler for Windows
      run: sudo apt-get install -y gcc-multilib gcc-mingw-w64

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golint
      run: go install golang.org/x/lint/golint@latest

    - name: Build
      run: make build windows-release test
